apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: go-sample-api
    newName: ghcr.io/trianggianggara/go-sample-api
    newTag: 9cbc90d
replicas:
  - name: go-sample-api
    count: 1
patches:
  - target:
      kind: Ingress
      name: go-sample-api
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev-api.angang.biz.id
