apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
images:
  - name: go-sample-api
    newName: ghcr.io/trianggianggara/go-sample-api
    newTag: d2xa41s
replicas:
  - name: go-sample-api
    count: 2
patches:
  - target:
      kind: Ingress
      name: go-sample-api
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging-api.angang.biz.id
